title: Config
type: object
properties:
  galleryName:
    type: string
    description: Main page title, the name for the gallery
  dashboardTilesCount:
    type: number
    description: Maximum number of tiles return for dashboard
  dashboardImageUrl:
    type: string
    description: Image presented on dashboard. If not set, the first image of last modified album is presented
required:
  - galleryName
  - dashboardTilesCount
