title: Settings
type: object
properties:
  galleryName:
    type: string
    description: Main page title, the name for the gallery
  authentication:
    type: boolean
    description: Defines if all user should authenticate before etner to gallery
  libraryDir:
    type: string
    description: Library directory
  dashboardTilesCount:
    type: number
    description: Maximum number of tiles return for dashboard
required:
  - galleryName
  - authentication
  - libraryDir
  - dashboardTilesCount
