title: Settings
type: object
properties:
  galleryName:
    type: string
    description: Main page title, the name for the gallery
  authentication:
    type: boolean
    description: Defines if all user should authenticate before etner to gallery
  language:
    type: string
    description: Language of gallery
  libraryDir:
    type: string
    description: Library directory
  dashboardTilesCount:
    type: number
    description: Maximum number of tiles return for dashboard
  dashboardImageUrl:
    type: string
    description: "Welcome img presented on dashboard screen.
                 If not set, the first image of last modified album is taken"
  thumbnailWidth:
    type: number
    description: Width of generated thumbnail, in pixels
  thumbnailQuality:
    type: number
    description: Quality of generated thumbnails, in percent
  imageDownload:
    type: boolean
    description: Defines if the user can download an image
