title: SettingsParam
type: object
properties:
  name:
    type: string
    description: Visible name of the field (eg. Gallery name)
  key:
    type: string
    description: field name of the parameter (eg. galleryName)
  description:
    type: string
    description: description of the parameter
  type:
    type: string
    enum:
      - string
      - number
      - boolean
required:
  - name
  - key
  - type
